# Generated by Django 3.0.6 on 2020-05-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=32, verbose_name='номер телефона')),
                ('email', models.EmailField(max_length=128, verbose_name='email')),
                ('city', models.CharField(default='Москва', max_length=32, verbose_name='город')),
                ('address', models.CharField(max_length=128, verbose_name='адрес')),
            ],
        ),
    ]
