# Generated by Django 2.2.12 on 2020-05-17 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_contact'),
    ]

    operations = [
    ]
